//! Code and script emission (R24): the system crate manifest (`CONFIG`,
//! `LAYOUT`, the `System` implementation), each Partition's manifest
//! (Resource cells, Context types, Job wrappers), the linker script with
//! its memory map (DD-07, DD-11), and the human-readable configuration
//! summary (R24.3). The emitted Rust contains no `unsafe` (R24.2): the
//! Resource cells use `rsk::ResourceCell`, whose `unsafe impl Sync` is
//! justified in the Kernel_Unsafe_Module (UJ-050).

use std::fmt::Write;

use crate::derive::{Generated, Kind, ReleaseSource, NO_SLOT};
use crate::layout::Region;
use crate::model::cs_sites;

fn resp(code: u8) -> &'static str {
    match code {
        0 => "RESP_END_JOB",
        1 => "RESP_RESTART_PARTITION",
        2 => "RESP_STOP_PARTITION",
        3 => "RESP_SAFE_STATE",
        4 => "RESP_RECORD_ONLY",
        _ => "RESP_RECORD_AND_CONTINUE",
    }
}

fn interval(r: &Region) -> String {
    format!("Interval {{ base: 0x{:08x}, size_log2: {} }}", r.base, r.size_log2)
}

/// The system crate manifest (expanded by `rsk_system!()` in the system
/// crate, which depends on `rsk-kernel` and every Partition crate).
pub fn system_source(g: &Generated) -> String {
    let nt = g.tasks.len();
    let nr = g.resources.len();
    let np = g.partitions.len();
    let mut s = String::new();
    let _ = writeln!(s, "// @generated by rsk-gen (Generated_Config, R24.1). Do not edit.");
    let _ = writeln!(s, "pub const NT: usize = {nt};");
    let _ = writeln!(s, "pub const NR: usize = {nr};");
    let _ = writeln!(s, "pub const NP: usize = {np};");
    let _ = writeln!(s, "pub const NL: usize = {};", g.lock_capacity);
    let _ = writeln!(s, "pub const NS: usize = {};", g.slot_count);
    let _ = writeln!(s, "pub const NE: usize = {};", g.log_capacity);
    let _ = writeln!(s, "/// Time-base ticks per second (R21.2).");
    let _ = writeln!(s, "pub const TICK_HZ: u64 = {};", g.target.tick_hz);
    let _ = writeln!(s, "pub const CPU_HZ: u64 = {};", g.target.cpu_hz);
    let _ = writeln!(s, "pub const CONFIG_CHECKSUM: u32 = 0x{:08x};", g.checksum);
    // The canonical table image and the checksum as link-level symbols, for
    // the Config_Checker's extraction from the binary (R26.4). `#[used]`
    // keeps them through section garbage collection; `no_mangle` is not an
    // unsafe attribute in the 2021 edition, so the system crate keeps
    // `#![forbid(unsafe_code)]` (R24.2).
    let image = crate::derive::config_bytes(g);
    let _ = writeln!(s, "/// Canonical image of the tables above (the bytes the checksum covers).");
    let _ = writeln!(s, "#[used]");
    let _ = writeln!(s, "#[no_mangle]");
    let _ = writeln!(s, "pub static RSK_CONFIG_IMAGE: [u8; {}] = [{}];", image.len(), image.iter().map(|b| format!("0x{b:02x}")).collect::<Vec<_>>().join(", "));
    let _ = writeln!(s, "#[used]");
    let _ = writeln!(s, "#[no_mangle]");
    let _ = writeln!(s, "pub static RSK_CONFIG_CHECKSUM: u32 = CONFIG_CHECKSUM;");
    let _ = writeln!(s, "pub const CONFIG: ::rsk_kernel::logic::Config<NT, NR, NP> = ::rsk_kernel::logic::Config {{");
    let _ = writeln!(s, "    tasks: [");
    for t in &g.tasks {
        let _ = writeln!(
            s,
            "        ::rsk_kernel::logic::TaskCfg {{ priority: {}, partition: {}, kind: {}, offset: {}, period: {}, deadline: {}, budget: {}, mit_policy: {}, fpu: {} }}, // {}",
            t.priority,
            t.partition,
            if t.kind == Kind::Periodic { "::rsk_kernel::logic::KIND_PERIODIC" } else { "::rsk_kernel::logic::KIND_SPORADIC" },
            t.offset_ticks,
            t.period_ticks,
            t.deadline_ticks,
            t.budget_cycles,
            match t.mit_policy {
                crate::decl::MitPolicy::Defer => "::rsk_kernel::logic::MIT_DEFER",
                crate::decl::MitPolicy::Discard => "::rsk_kernel::logic::MIT_DISCARD",
            },
            t.fpu,
            t.id
        );
    }
    let _ = writeln!(s, "    ],");
    let _ = writeln!(s, "    resources: [");
    for r in &g.resources {
        let _ = writeln!(s, "        ::rsk_kernel::logic::ResourceCfg {{ ceiling: {}, partition: {} }}, // {}", r.ceiling, r.partition, r.id);
    }
    let _ = writeln!(s, "    ],");
    let _ = writeln!(s, "    access: [");
    for t in &g.tasks {
        let row: Vec<&str> = (0..nr).map(|r| if t.resources.contains(&r) { "true" } else { "false" }).collect();
        let _ = writeln!(s, "        [{}],", row.join(", "));
    }
    let _ = writeln!(s, "    ],");
    let _ = writeln!(s, "    partitions: [");
    for p in &g.partitions {
        let _ = writeln!(
            s,
            "        ::rsk_kernel::logic::PartitionCfg {{ level: {}, fault_response: ::rsk_kernel::logic::{}, overrun_response: ::rsk_kernel::logic::{}, deadline_response: ::rsk_kernel::logic::{}, mit_threshold: {} }}, // {}",
            p.level.code(),
            resp(p.fault.code()),
            resp(p.overrun.code()),
            resp(p.deadline_miss.code()),
            p.mit_threshold,
            p.name
        );
    }
    let _ = writeln!(s, "    ],");
    let _ = writeln!(s, "    operating_duration: {},", g.operating_duration_ticks);
    let slots = |f: fn(&crate::derive::GenTask) -> u8| -> String {
        g.tasks.iter().map(|t| if f(t) == NO_SLOT { "::rsk_kernel::logic::NO_SLOT".to_string() } else { f(t).to_string() }).collect::<Vec<_>>().join(", ")
    };
    let _ = writeln!(s, "    slot_release: [{}],", slots(|t| t.slot_release));
    let _ = writeln!(s, "    slot_deadline: [{}],", slots(|t| t.slot_deadline));
    let _ = writeln!(s, "    slot_budget: [{}],", slots(|t| t.slot_budget));
    let _ = writeln!(s, "    slot_count: NS as u8,");
    let _ = writeln!(s, "}};");
    // Layout.
    let _ = writeln!(s, "use ::rsk_kernel::logic::mpu::{{Interval, Layout, PartitionLayout}};");
    let _ = writeln!(s, "const NO_WINDOW: Interval = Interval {{ base: 0, size_log2: 5 }};");
    let _ = writeln!(s, "pub const LAYOUT: Layout<NP> = Layout {{");
    let _ = writeln!(s, "    kernel_flash: {},", interval(&g.plan.kernel_flash));
    let _ = writeln!(s, "    shared_code: {},", interval(&g.plan.shared_code));
    let _ = writeln!(s, "    kernel_ram: {},", interval(&g.plan.kernel_ram));
    let _ = writeln!(s, "    partitions: [");
    for p in &g.plan.partitions {
        let mut windows: Vec<String> = p.windows.iter().map(|w| format!("Interval {{ base: 0x{:08x}, size_log2: {} }}", w.base, w.size_log2)).collect();
        while windows.len() < crate::layout::MAX_WINDOWS {
            windows.push("NO_WINDOW".to_string());
        }
        let _ = writeln!(
            s,
            "        PartitionLayout {{ code: {}, code_srd: 0x{:02x}, ram: {}, ram_srd: 0x{:02x}, stack_size: {}, windows: [{}], window_count: {} }}, // {}",
            interval(&p.code),
            p.code.srd,
            interval(&p.ram),
            p.ram.srd,
            p.stack,
            windows.join(", "),
            p.windows.len(),
            p.name
        );
    }
    let _ = writeln!(s, "    ],");
    let _ = writeln!(s, "}};");
    let _ = writeln!(s, "pub type K = ::rsk_kernel::arch::Bound<NT, NR, NP, NL, NS, NE>;");
    let views: Vec<&str> = (0..np).map(|_| "::rsk_kernel::arch::placeholder_view()").collect();
    let _ = writeln!(
        s,
        "static KERNEL: ::rsk_kernel::arch::cm4::KernelCell<K> = ::rsk_kernel::arch::cm4::KernelCell::new(::rsk_kernel::arch::Bound {{ cfg: CONFIG, kernel: ::rsk_kernel::arch::placeholder_kernel(), layout: LAYOUT, views: [{}] }});",
        views.join(", ")
    );
    let dispatch: Vec<String> = g.tasks.iter().map(|t| t.dispatch_irq.to_string()).collect();
    let _ = writeln!(s, "const DISPATCH_IRQ: [u16; NT] = [{}];", dispatch.join(", "));
    let intake: Vec<String> = g
        .tasks
        .iter()
        .map(|t| match &t.source {
            Some(ReleaseSource::Interrupt { irq, .. }) => irq.to_string(),
            _ => "0xFFFF".to_string(),
        })
        .collect();
    let _ = writeln!(s, "const INTAKE_IRQ: [u16; NT] = [{}];", intake.join(", "));
    let _ = writeln!(s, "pub struct Sys;");
    let _ = writeln!(s, "impl ::rsk_kernel::arch::System for Sys {{");
    let _ = writeln!(s, "    type K = K;");
    let _ = writeln!(s, "    const IRQ_COUNT: u16 = {};", g.target.irq_count);
    let _ = writeln!(s, "    const TIMER_VECTOR: u16 = 16 + {};", g.target.timer_irq);
    let _ = writeln!(s, "    const PRIORITY_BITS: u8 = {};", g.target.priority_bits);
    let _ = writeln!(s, "    const CONFIG_CHECKSUM: u32 = CONFIG_CHECKSUM;");
    let _ = writeln!(s, "    fn kernel() -> &'static ::rsk_kernel::arch::cm4::KernelCell<K> {{ &KERNEL }}");
    let _ = writeln!(s, "    fn task_entry(t: u8) -> fn() {{");
    let _ = writeln!(s, "        match t {{");
    for t in &g.tasks {
        let _ = writeln!(s, "            {} => {},", t.index, t.entry_path);
    }
    let _ = writeln!(s, "            _ => {},", g.tasks[0].entry_path);
    let _ = writeln!(s, "        }}");
    let _ = writeln!(s, "    }}");
    let _ = writeln!(s, "    fn binding(n: u16) -> ::rsk_kernel::arch::Binding {{");
    let _ = writeln!(s, "        if n == Self::TIMER_VECTOR {{ return ::rsk_kernel::arch::Binding::Kernel; }}");
    let _ = writeln!(s, "        let mut t = 0;");
    let _ = writeln!(s, "        while t < NT {{");
    let _ = writeln!(s, "            if n == 16 + DISPATCH_IRQ[t] {{ return ::rsk_kernel::arch::Binding::Dispatch(t as u8); }}");
    let _ = writeln!(s, "            if INTAKE_IRQ[t] != 0xFFFF && n == 16 + INTAKE_IRQ[t] {{ return ::rsk_kernel::arch::Binding::Intake {{ task: t as u8, partition: CONFIG.tasks[t].partition }}; }}");
    let _ = writeln!(s, "            t += 1;");
    let _ = writeln!(s, "        }}");
    let _ = writeln!(s, "        ::rsk_kernel::arch::Binding::Unbound");
    let _ = writeln!(s, "    }}");
    let _ = writeln!(s, "    fn dispatch_vector(t: u8) -> u16 {{ 16 + DISPATCH_IRQ[t as usize] }}");
    let _ = writeln!(s, "    fn intake_vector(t: u8) -> Option<u16> {{ if INTAKE_IRQ[t as usize] == 0xFFFF {{ None }} else {{ Some(16 + INTAKE_IRQ[t as usize]) }} }}");
    let _ = writeln!(s, "    fn stack_top(p: u8) -> u32 {{ let pl = LAYOUT.partitions[p as usize]; pl.ram.base + pl.stack_size }}");
    let _ = writeln!(s, "    fn stack_bottom(p: u8) -> u32 {{ LAYOUT.partitions[p as usize].ram.base }}");
    let _ = writeln!(s, "    fn safe_state() -> ! {{ {}() }}", g.safe_state);
    let _ = writeln!(s, "}}");
    s
}

/// The manifest of one Partition crate (expanded by `rsk_partition_<name>!()`
/// at the crate root): the Resource cells, one Context type per Task with
/// a `Shared` proxy per accessed Resource (R8.7), and the Job wrappers
/// that the system crate's task table points at.
pub fn partition_source(g: &Generated, p: usize) -> String {
    let part = &g.partitions[p];
    let mut s = String::new();
    let _ = writeln!(s, "// @generated by rsk-gen for Partition `{}`. Do not edit.", part.name);
    let _ = writeln!(s, "pub mod rsk_resources {{");
    for &r in &part.resources {
        let res = &g.resources[r];
        let _ = writeln!(
            s,
            "    /// Resource `{}` (Ceiling {}; accessed by {}).",
            res.id,
            res.ceiling,
            res.accessors.iter().map(|&t| g.tasks[t].name.clone()).collect::<Vec<_>>().join(", ")
        );
        let _ = writeln!(s, "    pub static {}: ::rsk::ResourceCell<{}> = ::rsk::ResourceCell::new({});", res.name.to_uppercase(), res.ty, res.init);
    }
    let _ = writeln!(s, "}}");
    let _ = writeln!(s, "pub mod rsk_ctx {{");
    for &t in &part.tasks {
        let task = &g.tasks[t];
        let _ = writeln!(s, "    /// The Context of Task `{}` (Priority {}).", task.id, task.priority);
        let _ = writeln!(s, "    pub struct {} {{", ctx_name(&task.name));
        for &r in &task.resources {
            let res = &g.resources[r];
            let _ = writeln!(s, "        pub {}: ::rsk::Shared<'static, {}>,", res.name, res.ty);
        }
        let _ = writeln!(s, "    }}");
    }
    let _ = writeln!(s, "}}");
    let _ = writeln!(s, "pub mod rsk_jobs {{");
    for &t in &part.tasks {
        let task = &g.tasks[t];
        let sites = cs_sites(g, t);
        let _ = writeln!(s, "    /// Job wrapper of `{}` (vector {}; Critical_Section sites: {}).", task.id, task.vector(), if sites.is_empty() { "none".to_string() } else { sites.join(", ") });
        let _ = writeln!(s, "    pub fn {}() {{", task.name);
        let _ = writeln!(s, "        super::{}(super::rsk_ctx::{} {{", task.name, ctx_name(&task.name));
        for &r in &task.resources {
            let res = &g.resources[r];
            let _ = writeln!(s, "            {}: ::rsk::Shared::new(&super::rsk_resources::{}, {}),", res.name, res.name.to_uppercase(), r);
        }
        let _ = writeln!(s, "        }})");
        let _ = writeln!(s, "    }}");
    }
    let _ = writeln!(s, "}}");
    s
}

/// `control` -> `Control`, `imu_read` -> `ImuRead`.
pub fn ctx_name(task: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for c in task.chars() {
        if c == '_' {
            upper = true;
            continue;
        }
        if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn archive(krate: &str) -> String {
    krate.replace('-', "_")
}

/// `memory.x`: the regions the linker script uses, with the usable bytes
/// of each (the enabled subregions).
pub fn memory_x(g: &Generated) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "/* @generated by rsk-gen: memory map of the Target `{}` (DD-07). */", g.target.name);
    let _ = writeln!(s, "MEMORY");
    let _ = writeln!(s, "{{");
    let _ = writeln!(s, "  KFLASH (rx)  : ORIGIN = 0x{:08x}, LENGTH = {}", g.plan.kernel_flash.base, g.plan.kernel_flash.usable);
    let _ = writeln!(s, "  SHARED (rx)  : ORIGIN = 0x{:08x}, LENGTH = {}", g.plan.shared_code.base, g.plan.shared_code.usable);
    for (i, p) in g.plan.partitions.iter().enumerate() {
        let _ = writeln!(s, "  P{i}CODE (rx)  : ORIGIN = 0x{:08x}, LENGTH = {}", p.code.base, p.code.usable);
    }
    let _ = writeln!(s, "  KRAM   (rwx) : ORIGIN = 0x{:08x}, LENGTH = {}", g.plan.kernel_ram.base, g.plan.kernel_ram.usable);
    for (i, p) in g.plan.partitions.iter().enumerate() {
        let _ = writeln!(s, "  P{i}RAM  (rwx) : ORIGIN = 0x{:08x}, LENGTH = {}", p.ram.base, p.ram.usable);
    }
    let _ = writeln!(s, "}}");
    s
}

/// `link.x`: places each crate's sections by archive name (DD-11).
pub fn link_x(g: &Generated, system_crate: &str) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "/* @generated by rsk-gen: linker script (DD-11). Kernel crates and the system crate");
    let _ = writeln!(s, "   in KFLASH/KRAM; each Partition crate in its own regions with the stack at the");
    let _ = writeln!(s, "   bottom of its RAM (R16.5); core, the rsk API and the shared trampolines in SHARED. */");
    let _ = writeln!(s, "INCLUDE memory.x");
    let _ = writeln!(s);
    let _ = writeln!(s, "ENTRY(Reset);");
    let _ = writeln!(s, "EXTERN(__RESET_VECTOR);");
    let _ = writeln!(s, "EXTERN(__EXCEPTIONS);");
    let _ = writeln!(s, "EXTERN(__INTERRUPTS);");
    let _ = writeln!(s);
    let _ = writeln!(s, "PROVIDE(_stack_start = ORIGIN(KRAM) + LENGTH(KRAM));");
    for (i, p) in g.plan.partitions.iter().enumerate() {
        let _ = writeln!(s, "PROVIDE(_p{i}_stack_top = ORIGIN(P{i}RAM) + {});", p.stack);
    }
    let _ = writeln!(s);
    let _ = writeln!(s, "SECTIONS");
    let _ = writeln!(s, "{{");
    let _ = writeln!(s, "  .vector_table ORIGIN(KFLASH) :");
    let _ = writeln!(s, "  {{");
    let _ = writeln!(s, "    LONG(_stack_start);");
    let _ = writeln!(s, "    KEEP(*(.vector_table.reset_vector));");
    let _ = writeln!(s, "    KEEP(*(.vector_table.exceptions));");
    let _ = writeln!(s, "    KEEP(*(.vector_table.interrupts));");
    let _ = writeln!(s, "  }} > KFLASH");
    let _ = writeln!(s);
    let _ = writeln!(s, "  .shared.rsk : ALIGN(4)");
    let _ = writeln!(s, "  {{");
    let _ = writeln!(s, "    KEEP(*(.text.rsk_shared .text.rsk_shared.*));");
    let _ = writeln!(s, "    . = ALIGN(4);");
    let _ = writeln!(s, "  }} > SHARED");
    for (i, p) in g.partitions.iter().enumerate() {
        let _ = writeln!(s);
        let _ = writeln!(s, "  .p{i}.text : ALIGN(4)");
        let _ = writeln!(s, "  {{");
        let _ = writeln!(s, "    *lib{}-*:*(.text .text.* .rodata .rodata.*)", archive(&p.krate));
        let _ = writeln!(s, "    . = ALIGN(4);");
        let _ = writeln!(s, "  }} > P{i}CODE");
    }
    let _ = writeln!(s);
    let _ = writeln!(s, "  .kernel.text : ALIGN(4)");
    let _ = writeln!(s, "  {{");
    let _ = writeln!(s, "    *librsk_kernel-*:*(.text .text.* .rodata .rodata.*)");
    let _ = writeln!(s, "    *librsk_entry-*:*(.text .text.* .rodata .rodata.*)");
    let _ = writeln!(s, "    *lib{}-*:*(.text .text.* .rodata .rodata.*)", archive(system_crate));
    let _ = writeln!(s, "    . = ALIGN(4);");
    let _ = writeln!(s, "  }} > KFLASH");
    let _ = writeln!(s);
    let _ = writeln!(s, "  .text : ALIGN(4)");
    let _ = writeln!(s, "  {{");
    let _ = writeln!(s, "    *(.text .text.*);");
    let _ = writeln!(s, "    . = ALIGN(4);");
    let _ = writeln!(s, "  }} > SHARED");
    let _ = writeln!(s);
    let _ = writeln!(s, "  .rodata : ALIGN(4)");
    let _ = writeln!(s, "  {{");
    let _ = writeln!(s, "    *(.rodata .rodata.*);");
    let _ = writeln!(s, "    . = ALIGN(4);");
    let _ = writeln!(s, "  }} > SHARED");
    for (i, p) in g.partitions.iter().enumerate() {
        let _ = writeln!(s);
        let _ = writeln!(s, "  .p{i}.bss ORIGIN(P{i}RAM) + {} (NOLOAD) : ALIGN(4)", g.plan.partitions[i].stack);
        let _ = writeln!(s, "  {{");
        let _ = writeln!(s, "    _p{i}_sbss = .;");
        let _ = writeln!(s, "    *lib{}-*:*(.bss .bss.* .data .data.* COMMON)", archive(&p.krate));
        let _ = writeln!(s, "    . = ALIGN(4);");
        let _ = writeln!(s, "    _p{i}_ebss = .;");
        let _ = writeln!(s, "  }} > P{i}RAM");
    }
    let _ = writeln!(s);
    let _ = writeln!(s, "  .kernel.data : ALIGN(4)");
    let _ = writeln!(s, "  {{");
    let _ = writeln!(s, "    _sdata = .;");
    let _ = writeln!(s, "    *(.data .data.*);");
    let _ = writeln!(s, "    . = ALIGN(4);");
    let _ = writeln!(s, "    _edata = .;");
    let _ = writeln!(s, "  }} > KRAM AT>KFLASH");
    let _ = writeln!(s, "  _sidata = LOADADDR(.kernel.data);");
    let _ = writeln!(s);
    let _ = writeln!(s, "  .kernel.bss (NOLOAD) : ALIGN(4)");
    let _ = writeln!(s, "  {{");
    let _ = writeln!(s, "    _sbss = .;");
    let _ = writeln!(s, "    *(.bss .bss.*);");
    let _ = writeln!(s, "    *(COMMON);");
    let _ = writeln!(s, "    . = ALIGN(4);");
    let _ = writeln!(s, "    _ebss = .;");
    let _ = writeln!(s, "  }} > KRAM");
    let _ = writeln!(s);
    let _ = writeln!(s, "  .rsk.tables : ALIGN(4)");
    let _ = writeln!(s, "  {{");
    let _ = writeln!(s, "    __rsk_bss_table = .;");
    let _ = writeln!(s, "    LONG(_sbss); LONG(_ebss); LONG(0);");
    for i in 0..g.partitions.len() {
        let _ = writeln!(s, "    LONG(_p{i}_sbss); LONG(_p{i}_ebss); LONG(0);");
    }
    let _ = writeln!(s, "    LONG(0); LONG(0); LONG(0);");
    let _ = writeln!(s, "    __rsk_data_table = .;");
    let _ = writeln!(s, "    LONG(_sdata); LONG(_edata); LONG(_sidata);");
    let _ = writeln!(s, "    LONG(0); LONG(0); LONG(0);");
    let _ = writeln!(s, "  }} > KFLASH");
    let _ = writeln!(s);
    let _ = writeln!(s, "  /DISCARD/ :");
    let _ = writeln!(s, "  {{");
    let _ = writeln!(s, "    *(.ARM.exidx .ARM.exidx.*);");
    let _ = writeln!(s, "    *(.ARM.extab .ARM.extab.*);");
    let _ = writeln!(s, "    *(.comment);");
    let _ = writeln!(s, "  }}");
    let _ = writeln!(s, "}}");
    s
}

/// The configuration summary (R24.3): every value of R24.1 for review.
pub fn summary(g: &Generated) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "rsk Generated_Config summary (R24.3)");
    let _ = writeln!(s, "Target: {} ({}), CPU {} Hz, time base {} Hz, {} priority bits, {} MPU regions", g.target.name, g.target.core_revision, g.target.cpu_hz, g.target.tick_hz, g.target.priority_bits, g.target.mpu_regions);
    let _ = writeln!(s, "Profile: {} {}", crate::profile_version::PROFILE_VERSION, g.variant);
    let _ = writeln!(s, "Operating duration: {} ticks", g.operating_duration_ticks);
    let _ = writeln!(s, "Safe state: {}", g.safe_state);
    let _ = writeln!(s, "Config checksum (CRC-32): 0x{:08x}", g.checksum);
    let _ = writeln!(s, "Capacities: lock stack {}, timer slots {}, event log {}", g.lock_capacity, g.slot_count, g.log_capacity);
    let _ = writeln!(s, "Kernel levels: {:?}; Task levels (level -> NVIC byte): {}", g.kernel_levels, g.priority_map.iter().map(|(l, n)| format!("{l} -> 0x{n:02x}")).collect::<Vec<_>>().join(", "));
    let _ = writeln!(s, "Kernel-owned peripherals: {}", g.target.peripherals.iter().filter(|p| p.kernel_owned).map(|p| p.name).collect::<Vec<_>>().join(", "));
    let _ = writeln!(s, "Timer: IRQ {} (vector {})", g.target.timer_irq, 16 + g.target.timer_irq);
    let _ = writeln!(s);
    let _ = writeln!(s, "Partitions:");
    for p in &g.partitions {
        let r = &g.plan.partitions[p.index];
        let _ = writeln!(s, "  {} (crate {}, level {}): fault {}, overrun {}, deadline miss {}, MIT threshold {}", p.name, p.krate, p.level.name(), p.fault.name(), p.overrun.name(), p.deadline_miss.name(), p.mit_threshold);
        let _ = writeln!(s, "    code {} bytes at 0x{:08x} (region 2^{}, srd 0x{:02x}); ram {} bytes at 0x{:08x} (region 2^{}, srd 0x{:02x}); stack {} bytes; init arena {} bytes", p.code_bytes, r.code.base, r.code.size_log2, r.code.srd, p.ram_bytes, r.ram.base, r.ram.size_log2, r.ram.srd, p.stack_bytes, p.init_arena);
        for w in &r.windows {
            let _ = writeln!(s, "    window 0x{:08x} (2^{}, srd 0x{:02x}, {}): {}", w.base, w.size_log2, w.srd, if w.read_only { "read-only" } else { "read-write" }, w.peripherals.join(", "));
        }
    }
    let _ = writeln!(s);
    let _ = writeln!(s, "Tasks:");
    for t in &g.tasks {
        let kind = match t.kind {
            Kind::Periodic => format!("periodic, offset {} ticks, period {} ticks", t.offset_ticks, t.period_ticks),
            Kind::Sporadic => format!(
                "sporadic, MIT {} ticks, policy {}, source {}",
                t.period_ticks,
                t.mit_policy.name(),
                match &t.source {
                    Some(ReleaseSource::Interrupt { peripheral, irq }) => format!("interrupt {peripheral} (IRQ {irq})"),
                    Some(ReleaseSource::Signal(sg)) => format!("signal {sg}"),
                    None => "none".to_string(),
                }
            ),
        };
        let _ = writeln!(s, "  {} (#{}, Partition {}, Priority {}, vector {}): {}, deadline {} ticks, Budget {} cycles, fpu {}, Resources [{}], nesting depth {}, slots release {} deadline {} budget {}", t.id, t.index, g.partitions[t.partition].name, t.priority, t.vector(), kind, t.deadline_ticks, t.budget_cycles, t.fpu, t.resources.iter().map(|&r| g.resources[r].name.clone()).collect::<Vec<_>>().join(", "), t.nesting_depth, slot_text(t.slot_release), slot_text(t.slot_deadline), slot_text(t.slot_budget));
    }
    let _ = writeln!(s);
    let _ = writeln!(s, "Resources:");
    for r in &g.resources {
        let _ = writeln!(s, "  {} (#{}, Partition {}, type {}): Ceiling {}, accessors [{}]", r.id, r.index, g.partitions[r.partition].name, r.ty, r.ceiling, r.accessors.iter().map(|&t| g.tasks[t].name.clone()).collect::<Vec<_>>().join(", "));
    }
    if !g.changes.is_empty() {
        let _ = writeln!(s);
        let _ = writeln!(s, "Conversions that changed a value (R21.2):");
        for c in &g.changes {
            let _ = writeln!(s, "  {}: {} {} -> {} {}", c.what, c.declared.value, c.declared.unit.name(), c.converted, c.unit);
        }
    }
    s
}

fn slot_text(s: u8) -> String {
    if s == NO_SLOT {
        "-".to_string()
    } else {
        s.to_string()
    }
}
