// @generated by `cargo xtask profile` from profile/profile.toml. Do not edit.
//! The Profile version that `rsk-kernel` implements (R1.4, R3.5, R6.7).
#![forbid(unsafe_code)]

/// The Profile version identifier (changes whenever the Profile changes, never reused).
pub const PROFILE_VERSION: &str = "0.3";
/// The default Profile_Variant.
pub const PROFILE_DEFAULT_VARIANT: &str = "Ravenscar";
/// Every Profile_Variant the Profile defines.
pub const PROFILE_VARIANTS: &[&str] = &["Ravenscar", "Jorvik"];
/// SHA-256 of the Profile source at this version.
pub const PROFILE_CONTENT_HASH: &str = "sha256:eb3e65422996d44833a51aa5e5039ecd68a535158073fba8227d6217027f4e05";
